repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # the release, git tag, or commit you want to use
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace


  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.2
    hooks:
      - id: ruff
      - id: ruff-format
