name: technical-indicators-pipeline-historical
networks:
  redpanda-network:
    external: true
    name: redpanda_network

services:
  trades:
    image: trades
    build:
      context: ../services/trades
    #env_file:
      #- ../services/trades/settings.env
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda:9092
      - KAFKA_TOPIC=trades_historical_${RUN_ID}
      - PAIRS=["BTC/USD", "BTC/EUR", "ETH/EUR", "ETH/USD", "ETH/BTC", "SOL/USD", "XRP/USD", "DOGE/USD"]
      - DATA_SOURCE=historical
      - LAST_N_DAYS=30
    restart: on-failure
    networks:
      - redpanda-network

  candles:
    image: candles
    build:
      context: ../services/candles
    #env_file:
      #- ../services/candles/settings.env
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda:9092
      - KAFKA_INPUT_TOPIC=trades_historical_${RUN_ID}
      - KAFKA_OUTPUT_TOPIC=candles_historical_${RUN_ID}
      - KAFKA_CONSUMER_GROUP=candles_historical_${RUN_ID}
      - CANDLE_INTERVAL_SECONDS=60
      - EMIT_INCOMPLETE_CANDLES=False
      - DATA_SOURCE=historical
    # TODO restart: on-failure // add a retry mechanism LINKED WITH THE QUIX STREAMS STATEFUL SOURCE METHOD in run.py
    networks:
      - redpanda-network

  technical-indicators:
    image: technical-indicators
    build:
      context: ../services/technical-indicators
    #env_file:
      #- ../services/technical-indicators/settings.env
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda:9092
      - KAFKA_INPUT_TOPIC=candles_historical_${RUN_ID}
      - KAFKA_OUTPUT_TOPIC=technical-indicators_historical_${RUN_ID}
      - KAFKA_CONSUMER_GROUP=technical_indicators_historical_${RUN_ID}
      - NUM_CANDLES_IN_STATE=120
      - CANDLE_INTERVAL_SECONDS=60
      - DATA_SOURCE=historical
    restart: on-failure
    networks:
      - redpanda-network

  to-feature-store:
    image: to-feature-store
    build:
      context: ../services/to-feature-store
    env_file:
      - ../services/to-feature-store/hopsworks_credentials.env
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda:9092
      - KAFKA_INPUT_TOPIC=technical-indicators_historical_${RUN_ID}
      - KAFKA_CONSUMER_GROUP=to_feature_store_consumer_group_historical_${RUN_ID}
      - FEATURE_GROUP_NAME=technical_indicators
      - FEATURE_GROUP_VERSION=2
      - FEATURE_GROUP_PRIMARY_KEYS=["pair","candle_interval_seconds"]
      - FEATURE_GROUP_EVENT_TIME=timestamp_ms
      - FEATURE_GROUP_MATERIALIZATION_MINUTES=15
      - DATA_SOURCE=historical
    restart: on-failure
    networks:
      - redpanda-network
