name: technical-indicators-pipeline
networks:
  redpanda-network:
    external: true
    name: redpanda_network

services:
  trades:
    image: trades
    build:
      context: ../services/trades
    env_file:
      - ../services/trades/settings.env
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda:9092
    restart: always
    networks:
      - redpanda-network


  candles:
    image: candles
    build:
      context: ../services/candles
    env_file:
      - ../services/candles/settings.env
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda:9092
    restart: always
    networks:
      - redpanda-network


  technical-indicators:
    image: technical-indicators
    build:
      context: ../services/technical-indicators
    env_file:
      - ../services/technical-indicators/settings.env
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda:9092
    restart: always
    networks:
      - redpanda-network


  to-feature-store:
    image: to-feature-store
    build:
      context: ../services/to-feature-store
    env_file:
        - ../services/to-feature-store/settings.env
        - ../services/to-feature-store/hopsworks_credentials.env
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda:9092
    restart: always
    networks:
      - redpanda-network
